<?php
/**
 * @file
 * Countries dependency injection demonstration using FIFA listing.
 *
 * @see http://drupal.org/node/2019329
 * @see http://symfony.com/doc/current/cookbook/bundles/override.html
 * @see http://en.wikipedia.org/wiki/List_of_FIFA_country_codes
 * @see http://en.wikipedia.org/wiki/Comparison_of_IOC,_FIFA,_and_ISO_3166_country_codes
 *
 * @see Drupal\Core\DependencyInjection\Compiler\RegisterNestedMatchersPass
 */
